### PR TITLE
Remove unnecessary repopulating of Book-bean

### LINKED ISSUE #427: Unable to change the name of an author
**Describe the bug**

An exception is thrown when there is an attempt to try to change the name of an author.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in 
2. Go to 'My books'
2. Select a shelf
3. Click on a row
4. Change the name of an author's first or last name
5. See error

**Expected behaviour**

The name should be changed and the grid should update to show the new name.

**Additional context**

Stack trace: https://gist.github.com/knjk04/360e5f6acd35dedaa3c2c26b4d1bd2c3

---

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw).

Please note that this may be tricky to debug and fix

### PR DESCRIPTION
**Pull request by schrothbn**
Removed unnecessary repopulating of Book-bean in BookForm to correctly save data for existing Books

## Summary of change

BookBean in BookForm is repopulated no matter if it's still created populated (e.g. because the Book already exists and given to the form form outside). 

## Additional context

The exception mentioned in the issue is not reproducible, different error was still thrown and author name changes didn't work as intended.

## Related issue

Closes #427 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [ ] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [ ] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### CODE REVIEW

**Comment by knjk04** [comment]
@schrothbn Thanks for working on this! We'll review this once we've determined whether this is the root cause

**Comment by schrothbn** [comment]
@knjk04 After further looking into it i think the whole populating of the BookBean and resetting it to the binder, doesn't do anything. After looking futher into this, that change also resolves the error on linux, we might want to remove the whole populating of the Book there though.

**Comment by knjk04** [comment]
> After looking futher into this, that change also resolves the error on linux, we might want to remove the whole populating of the Book there though.

Sorry, I didn't quite understand this. Are you saying that populating the `Book` bean fixes the problem you're facing on Linux?

**Comment by schrothbn** [comment]
@knjk04  I'm very sorry if i'm confusing. I'll try to make it clearer:
The stacktrace associated with the issue on #427 only occurs in that form on linux.
It occurs in the setBookBean-Method while binder.setBean is called. 
What i'm saying was, that this whole part
```
 Book book = populateBookBean();
 if (book != null) {
    binder.setBean(book);
 }
```
can actually be removed, as it causes the error by setting a new Book on the binder, which in any case i tested already has a populated one with all updated values anyway. 
That also saves a new Book in the database everytime instead of updating an existing one if needed.
Hope that explains it. 

The change in this PR fixes the problem #427 under Linux as well but probably that code should be removed in the long run.

**Comment by knjk04** [comment]
@schrothbn Thanks for clarifying. I think the reason I misunderstood you is that I'm facing this issue on Windows with Oracle JDK 11.0.7. I can also test this on Linux to see whether I'm getting the same error.

I'll take a look into this PR shortly.

**Comment by knjk04** [comment]
I'm also getting this on Linux (Fedora) with OpenJDK 11.0.8)

**Comment by knjk04** [comment]
@schrothbn I want to take a deeper dive into this, so I'll take a look at this over the weekend

File: src/main/java/com/karankumar/bookproject/ui/book/BookForm.java [hunk 1]
```diff
@@ -355,9 +355,12 @@ private boolean isMovedToDifferentShelf() {
...
     private void setBookBean() {
-        Book book = populateBookBean();
-        if (book != null) {
-            binder.setBean(book);
+        // Only repopulate if we create a new Book
+        if (binder.getBean() == null) {
+            Book book = populateBookBean();
+            if (book != null) {
+                binder.setBean(book);
+            }
```
Comment (knjk04) [inline src/main/java/com/karankumar/bookproject/ui/book/BookForm.java:363]: Could you please move this into the `else` below? We don't need to check whether the bean in the binder is null twice

**Review by knjk04 — APPROVED** [review]
Apologies for the delay in reviewing this.

Thanks a lot for fixing this! This works for me on Windows. There's one suggestion I made for improvement, but since it's only one thing, I'll go ahead and fix it.
